/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Chart: typeof import('./src/components/Chart.vue')['default']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElTabPane: typeof import('element-plus/es')['ElTabPane']
    ElTabs: typeof import('element-plus/es')['ElTabs']
    Form: typeof import('./src/components/Form.vue')['default']
    Header: typeof import('./src/components/Header.vue')['default']
    Loading: typeof import('./src/components/Loading.vue')['default']
    NotificationBell: typeof import('./src/components/NotificationBell.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./src/components/Sidebar.vue')['default']
    Table: typeof import('./src/components/Table.vue')['default']
    Toast: typeof import('./src/components/Toast.vue')['default']
  }
}

// For TSX support
declare global {
  const Chart: typeof import('./src/components/Chart.vue')['default']
  const ElButton: typeof import('element-plus/es')['ElButton']
  const ElCard: typeof import('element-plus/es')['ElCard']
  const ElDialog: typeof import('element-plus/es')['ElDialog']
  const ElForm: typeof import('element-plus/es')['ElForm']
  const ElFormItem: typeof import('element-plus/es')['ElFormItem']
  const ElInput: typeof import('element-plus/es')['ElInput']
  const ElLink: typeof import('element-plus/es')['ElLink']
  const ElTabPane: typeof import('element-plus/es')['ElTabPane']
  const ElTabs: typeof import('element-plus/es')['ElTabs']
  const Form: typeof import('./src/components/Form.vue')['default']
  const Header: typeof import('./src/components/Header.vue')['default']
  const Loading: typeof import('./src/components/Loading.vue')['default']
  const NotificationBell: typeof import('./src/components/NotificationBell.vue')['default']
  const RouterLink: typeof import('vue-router')['RouterLink']
  const RouterView: typeof import('vue-router')['RouterView']
  const Sidebar: typeof import('./src/components/Sidebar.vue')['default']
  const Table: typeof import('./src/components/Table.vue')['default']
  const Toast: typeof import('./src/components/Toast.vue')['default']
}